default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1

development:
  <<: *default
  database: api_exemple_development

test:
  <<: *default
  database: api_exemple_test

production:
  <<: *default
  database: api_exemple_production
  username: api_exemple
  password: <%= ENV['API_EXEMPLE_DATABASE_PASSWORD'] %>
